name: Build & Upload gsbMonolith
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build_upload:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Inject AWS secrets in Database.cs
        shell: pwsh
        run: |
          $file = Get-ChildItem -Recurse -Filter "Database.cs" | Select-Object -First 1
          if (-not $file) {
            Write-Error "Database.cs introuvable !"
          }

          (Get-Content $file.FullName -Raw)
            .Replace("__AWS_HOST__", "${{ secrets.AWS_HOST }}")
            .Replace("__AWS_USER__", "${{ secrets.AWS_USER }}")
            .Replace("__AWS_PASSWORD__", "${{ secrets.AWS_PASSWORD }}") |
            Set-Content $file.FullName

          Write-Host "✔ Secrets AWS injectés dans Database.cs"


      
      
      - name: Restore
        run: dotnet restore
      
      - name: Build & Publish EXE
        run: |
          dotnet publish GSB-manager/GSB-manager.csproj `
            -c Release `
            -r win-x64 `
            --self-contained true `
            /p:PublishSingleFile=true `
            /p:IncludeAllContentForSelfExtract=true `
            -o publish
      
      - name: Rename exe
        run: |
          ren publish\GSB-manager.exe GSB-manager-${{ github.ref_name }}.exe
      
      - name: Upload exe to existing GitHub release
        shell: bash
        run: |
          gh release upload "${{ github.ref_name }}" "publish/GSB-manager-${{ github.ref_name }}.exe" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}